version: '3.8'

services:
  phonebook-app:
    build: .
    image: phonebook-app:latest
    container_name: phonebook-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/phonebook_db
    depends_on:
      - mongo
    command: ["java", "-jar", "/app/phonebook-api-0.0.1-SNAPSHOT.jar"]

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: phonebook_db

volumes:
  mongo-data:
